### PR TITLE
Added build target osx-lib to build an OSX static library.

### PR DESCRIPTION
**Pull request by fdeantoni**
To make development with Zenroom on OSX easier, I created a build target to create a static library for OSX. I'm not familiar with all clang build parameters, but so far the generated static library seems to work well in other projects (C, Rust).

### CODE REVIEW

**Comment by fdeantoni** [comment]
Hi @puria, I can do that, but is seems to section on "static builds" is out of date as it mentions targets such as `bootstrap`, `static`, and `check-static` which I think dont exist anymore?

**Comment by puria** [comment]
thanks @fdeantoni just added a separate issue to update the static targets as soon as we can (or if you also want to take care ;p). In the meantime you can go with the osx-lib, so I'll merge this PR.

**Comment by puria** [comment]
@fdeantoni do you also have a concrete usage example? So we can put a super quick small test fixture (to run on the CI).

**Comment by fdeantoni** [comment]
Hi @puria, the example I have is a small project to create Rust bindings for Zenroom, see here: [zenroom.rs](https://github.com/fdeantoni/zenroom-rs). Not sure if this is what you were looking for though. I created the osx-lib build target to make development of this library slightly easier (as I develop on OSX).

**Comment by puria** [comment]
Enough then ;)

**Comment by andrea-dintino** [comment]
@fdeantoni thanks for the contribution! We have a channel about Zenroom on Telegram, you're most welcome to join: https://t.me/zenroom

**Pull request merged**
