### PR TITLE
ADD target to create shared library for android

### PR DESCRIPTION
**Pull request by kozko2001**

### CODE REVIEW

**Comment by jaromil** [comment]
Cheers! Seems good to me, also the failed test seems unrelated (segfault on ecdh.lua on OSX).
Re-running it now.

**Comment by jaromil** [comment]
Two quick questions:

1. Do you have an Apple/OSX machine to run 'make check-shared' tests locally and verify what this failure is about?

2. Can you please add some small documentation on the ios and android build process in the wiki?
inside the Build page here https://github.com/DECODEproject/zenroom/wiki/Build
anything understandable by other developers will do.

thanks!

**Comment by kozko2001** [comment]
1. I did, and it failed first time (I suppose because the .a where built
for the arm architecture and there was no clean before) after the "make
clean; make shared; make check-shared" did work :D

  Maybe what is happening is that the test is somehow using a "dirty"
libraries made for arm?

2. Done :)

**Comment by jaromil** [comment]
cheers!

**Pull request merged**
